FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive TZ=UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libtool autotools-dev automake autoconf pkg-config \
    bsdmainutils python3 curl ca-certificates git unzip zip file rsync \
    libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools qtbase5-dev \
    libqrencode-dev libzmq3-dev libminiupnpc-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY . /src

CMD ["/bin/bash"]