FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive TZ=UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libtool autotools-dev automake autoconf pkg-config \
    bsdmainutils python3 curl ca-certificates git unzip zip file rsync \
    make cmake patch \
    g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY . /src

CMD ["/bin/bash"]
