FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y     build-essential libtool autotools-dev automake pkg-config bsdmainutils python3     libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev     libboost-chrono-dev libboost-test-dev libboost-thread-dev     libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5     qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler     curl ca-certificates git ccache     && rm -rf /var/lib/apt/lists/*

WORKDIR /src
ENV CCACHE_DIR=/src/.ccache
