name: Docker Build & Check

on:
  push:
    branches: [ master, main, palladium-2026-core ]
  pull_request:
    branches: [ master, main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-build/Dockerfile
          push: false
          tags: palladium-core:latest
